#!/usr/bin/env bash
# redirecting /redirect_me to another page
#46  try_files $uri $uri/ =404;
sudo apt-get -y update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
sudo sed -i '46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
