#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page1" | sudo tee /usr/share/nginx/html/custom_404.html

sudo sed -i '49i error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo sed -i '50i location = /custom_404.html {' /etc/nginx/sites-available/default
sudo sed -i '51i root /usr/share/nginx/html;' /etc/nginx/sites-available/default
sudo sed -i '52i internal;' /etc/nginx/sites-available/default
sudo sed -i '53i }' /etc/nginx/sites-available/default
sudo service nginx restart