#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get install -y haproxy=2.0.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend http_back\n\tbalance roundrobin\n\tserver 1586-web-01 34.74.192.152:80 check\n\tserver 1586-web-02 35.237.243.141:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
