#!/usr/bin/env bash
# set nginx to listen on port 80
sudo sed -i -e '21s/8080/80/' /etc/nginx/sites-enabled/default
sudo sed -i -e '22s/8080/80/' /etc/nginx/sites-enabled/default
sudo service nginx restart
