#!/usr/bin/env bash
# sript with different trap conditions

echo $$ > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command";rm /var/run/holbertonscript.pid; exit' SIGTERM #pkill
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT #If we apply a function

print="To infinity and beyond"
while true;do
        echo "$print"
        sleep 2
done