#!/usr/bin/env bash
# script that displays: To infinity and beyond indefinitely With a sleep 2 in between each iteration I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' 15
inf="To infinity and beyond"
cont=1
while [ $cont -le 3 ];do
        echo "$inf"
        cont=$(( cont-1 ))
        sleep 2
done