#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

min=0
hour=0
while [ $hour -le 12 ];do
        echo "Hour: $hour"
        while [ $min -lt 59 ];do
                (( min+=1 ))
                echo "$min"
        done
        min=0
        (( hour++ ))
done