#!/usr/bin/env bash
# checking different conditions for a file

FILE="holbertonschool"
# -e Check for file existence, regardless of type (node, directory, socket, etc.)
if [ -e $FILE ];then
        echo "holbertonschool file exists"
        # -s True if the FILE exists and has nonzero size.
        if [ ! -s $FILE ];then
                echo "holbertonschool file is empty"
        else
                echo "holbertonschool file is not empty"
        fi
        #-f Check for regular file existence not a directory
        if [ -f $FILE ];then
                echo "holbertonschool is a regular file"
        fi
else
        echo "holbertonschool file does not exist"
fi