#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements.
cp /etc/hosts /etc/hosts_old
cat /etc/hosts > hosts_new
sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' hosts_new
echo "8.8.8.8 facebook.com" >> hosts_new
cp -f hosts_new /etc/hosts
